{
  "type": "Lambda-Py",
  "results": {
    "original/k-python/programs/testassign9.py": {
      "identifier": "original/k-python/programs/testassign9.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 1, Column 3, Position 4):\n'#hasheq((ctx . #hasheq((nodetype . \"Store\")))\n         (nodetype . \"Starred\")\n         (value\n          .\n          #hasheq((ast\n                   .\n                   #hasheq((ctx . #hasheq((nodetype . \"Store\")))\n                           (id . \"y\")\n                           (nodetype . \"Name\")))\n                  (column . 4)\n                  (line . 1)\n                  (nodetype . \"SrcLoc\")\n                  (position . 5)\n                  (span . 1))))\n  context...:\n   f348\n   f860\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign8.py": {
      "identifier": "original/k-python/programs/testassign8.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 1, Column 6, Position 7):\n'#hasheq((ctx . #hasheq((nodetype . \"Store\")))\n         (nodetype . \"Starred\")\n         (value\n          .\n          #hasheq((ast\n                   .\n                   #hasheq((ctx . #hasheq((nodetype . \"Store\")))\n                           (id . \"c\")\n                           (nodetype . \"Name\")))\n                  (column . 8)\n                  (line . 1)\n                  (nodetype . \"SrcLoc\")\n                  (position . 9)\n                  (span . 1))))\n  context...:\n   f348\n   f860\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign10.py": {
      "identifier": "original/k-python/programs/testassign10.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 4, Column 3, Position 27):\n'#hasheq((ctx . #hasheq((nodetype . \"Store\")))\n         (nodetype . \"Starred\")\n         (value\n          .\n          #hasheq((ast\n                   .\n                   #hasheq((ast\n                            .\n                            #hasheq((attr . \"x\")\n                                    (ctx . #hasheq((nodetype . \"Store\")))\n                                    (nodetype . \"Attribute\")\n                                    (value\n                                     .\n                                     #hasheq((ast\n                                              .\n                                              #hasheq((ctx\n                                                       .\n                                                       #hasheq((nodetype\n                                                                .\n                                                                \"Load\")))\n                                                      (id . \"b\")\n                                                      (nodetype . \"Name\")))\n                                             (column . 5)\n                                             (line . 4)\n                                             (nodetype . \"SrcLoc\")\n                                             (position . 29)\n                                             (span . 1)))))\n                           (column . 5)\n                           (line . 4)\n                           (nodetype . \"SrcLoc\")\n                           (position . 29)\n                           (span . 3)))\n                  (column . 5)\n                  (line . 4)\n                  (nodetype . \"SrcLoc\")\n                  (position . 29)\n                  (span . 3))))\n  context...:\n   f348\n   f860\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassert3.py": {
      "identifier": "original/k-python/programs/testassert3.py",
      "stdout": "",
      "stderr": "exception: Arity mismatch: expected '(), received 0, 0, 1\n",
      "returncode": 1,
      "exception": "exception",
      "message": " Arity mismatch: expected '(), received 0, 0, 1",
      "timeout": false
    },
    "original/k-python/programs/testassign3.py": {
      "identifier": "original/k-python/programs/testassign3.py",
      "stdout": "",
      "stderr": "exception: can't assign to literals\n",
      "returncode": 1,
      "exception": "exception",
      "message": " can't assign to literals",
      "timeout": false
    },
    "original/k-python/programs/testaugassign1.py": {
      "identifier": "original/k-python/programs/testaugassign1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign6.py": {
      "identifier": "original/k-python/programs/testassign6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign1.py": {
      "identifier": "original/k-python/programs/testassign1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign5.py": {
      "identifier": "original/k-python/programs/testassign5.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testassign4.py": {
      "identifier": "original/k-python/programs/testassign4.py",
      "stdout": "",
      "stderr": "exception: can't assign to literals\n",
      "returncode": 1,
      "exception": "exception",
      "message": " can't assign to literals",
      "timeout": false
    },
    "original/k-python/programs/testassign7.py": {
      "identifier": "original/k-python/programs/testassign7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassert1.py": {
      "identifier": "original/k-python/programs/testassert1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testall.py": {
      "identifier": "original/k-python/programs/testall.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassign2.py": {
      "identifier": "original/k-python/programs/testassign2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testany.py": {
      "identifier": "original/k-python/programs/testany.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testassert2.py": {
      "identifier": "original/k-python/programs/testassert2.py",
      "stdout": "",
      "stderr": "ImportError: module builtins not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module builtins not found",
      "timeout": false
    },
    "original/k-python/programs/testaugassign10.py": {
      "identifier": "original/k-python/programs/testaugassign10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign11.py": {
      "identifier": "original/k-python/programs/testaugassign11.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign12.py": {
      "identifier": "original/k-python/programs/testaugassign12.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign2.py": {
      "identifier": "original/k-python/programs/testaugassign2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign3.py": {
      "identifier": "original/k-python/programs/testaugassign3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign5.py": {
      "identifier": "original/k-python/programs/testaugassign5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign7.py": {
      "identifier": "original/k-python/programs/testaugassign7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign6.py": {
      "identifier": "original/k-python/programs/testaugassign6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign4.py": {
      "identifier": "original/k-python/programs/testaugassign4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools1.py": {
      "identifier": "original/k-python/programs/testbools1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign9.py": {
      "identifier": "original/k-python/programs/testaugassign9.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools2.py": {
      "identifier": "original/k-python/programs/testbools2.py",
      "stdout": "",
      "stderr": "exception: class %type has no attribute __name__\n",
      "returncode": 1,
      "exception": "exception",
      "message": " class %type has no attribute __name__",
      "timeout": false
    },
    "original/k-python/programs/testbools3.py": {
      "identifier": "original/k-python/programs/testbools3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testaugassign8.py": {
      "identifier": "original/k-python/programs/testaugassign8.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools10.py": {
      "identifier": "original/k-python/programs/testbools10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools11.py": {
      "identifier": "original/k-python/programs/testbools11.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testbools4.py": {
      "identifier": "original/k-python/programs/testbools4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools5.py": {
      "identifier": "original/k-python/programs/testbools5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbytes1.py": {
      "identifier": "original/k-python/programs/testbytes1.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 1, Column 7, Position 8):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'foo'\"))))\n  context...:\n   f1001\n   f822\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbytes2.py": {
      "identifier": "original/k-python/programs/testbytes2.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 1, Column 7, Position 8):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'f'\"))))\n  context...:\n   f1044\n   f1001\n   f822\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbytes4.py": {
      "identifier": "original/k-python/programs/testbytes4.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 10, Column 21, Position 201):\n'#hasheq((nodetype . \"Bytes\")\n         (s\n          .\n          #hasheq((nodetype . \"Bytes\") (value . \"b'\\\\x04\\\\x03\\\\x02\\\\x01'\"))))\n  context...:\n   f1001\n   f822\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools6.py": {
      "identifier": "original/k-python/programs/testbools6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbytes5.py": {
      "identifier": "original/k-python/programs/testbytes5.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 4, Column 4, Position 47):\n'#hasheq((nodetype . \"Bytes\")\n         (s\n          .\n          #hasheq((nodetype . \"Bytes\")\n                  (value . \"b'\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00'\"))))\n  context...:\n   f860\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools8.py": {
      "identifier": "original/k-python/programs/testbools8.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools7.py": {
      "identifier": "original/k-python/programs/testbools7.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testbools9.py": {
      "identifier": "original/k-python/programs/testbools9.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclasses1.py": {
      "identifier": "original/k-python/programs/testclasses1.py",
      "stdout": "",
      "stderr": "exception: class %type has no attribute __doc__\n",
      "returncode": 1,
      "exception": "exception",
      "message": " class %type has no attribute __doc__",
      "timeout": false
    },
    "original/k-python/programs/testbytes3.py": {
      "identifier": "original/k-python/programs/testbytes3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testcallable.py": {
      "identifier": "original/k-python/programs/testcallable.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclasses4.py": {
      "identifier": "original/k-python/programs/testclasses4.py",
      "stdout": "",
      "stderr": "exception: name 'exec' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'exec' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testclasses6.py": {
      "identifier": "original/k-python/programs/testclasses6.py",
      "stdout": "",
      "stderr": "ImportError: module types not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module types not found",
      "timeout": false
    },
    "original/k-python/programs/testclasses5.py": {
      "identifier": "original/k-python/programs/testclasses5.py",
      "stdout": "",
      "stderr": "ImportError: module types not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module types not found",
      "timeout": false
    },
    "original/k-python/programs/testclasses7.py": {
      "identifier": "original/k-python/programs/testclasses7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclasses9.py": {
      "identifier": "original/k-python/programs/testclasses9.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclassmethod.py": {
      "identifier": "original/k-python/programs/testclassmethod.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclasses8.py": {
      "identifier": "original/k-python/programs/testclasses8.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testcompile2.py": {
      "identifier": "original/k-python/programs/testcompile2.py",
      "stdout": "",
      "stderr": "exception: name 'eval' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'eval' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testcoercion1.py": {
      "identifier": "original/k-python/programs/testcoercion1.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testcompile1.py": {
      "identifier": "original/k-python/programs/testcompile1.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testdel.py": {
      "identifier": "original/k-python/programs/testdel.py",
      "stdout": "",
      "stderr": "desugar: We don't know how to delete this yet: (LexTuple (list (LexGlobalId 'c 'Del) (LexList (list (LexGlobalId 'd 'Del) (LexTuple (list (LexGlobalId 'e 'Del)))))))\n  context...:\n   loop\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   make-global-lets\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testcoercion2.py": {
      "identifier": "original/k-python/programs/testcoercion2.py",
      "stdout": "",
      "stderr": "exception: name 'NotImplemented' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'NotImplemented' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testclasses3.py": {
      "identifier": "original/k-python/programs/testclasses3.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testdocstring.py": {
      "identifier": "original/k-python/programs/testdocstring.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 21, Column 2, Position 174):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'5'\"))))\n  context...:\n   f682\n   loop\n   [repeats 1 more time]\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testdecorator.py": {
      "identifier": "original/k-python/programs/testdecorator.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testdicts2.py": {
      "identifier": "original/k-python/programs/testdicts2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testclasses2.py": {
      "identifier": "original/k-python/programs/testclasses2.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testcomprehensions.py": {
      "identifier": "original/k-python/programs/testcomprehensions.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testeval1.py": {
      "identifier": "original/k-python/programs/testeval1.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testeval3.py": {
      "identifier": "original/k-python/programs/testeval3.py",
      "stdout": "",
      "stderr": "exception: name 'eval' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'eval' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testeval4.py": {
      "identifier": "original/k-python/programs/testeval4.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testeval5.py": {
      "identifier": "original/k-python/programs/testeval5.py",
      "stdout": "",
      "stderr": "exception: name 'eval' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'eval' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testeval2.py": {
      "identifier": "original/k-python/programs/testeval2.py",
      "stdout": "",
      "stderr": "exception: name 'eval' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'eval' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testexec1.py": {
      "identifier": "original/k-python/programs/testexec1.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testexec3.py": {
      "identifier": "original/k-python/programs/testexec3.py",
      "stdout": "",
      "stderr": "exception: name 'exec' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'exec' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testexec4.py": {
      "identifier": "original/k-python/programs/testexec4.py",
      "stdout": "",
      "stderr": "exception: name 'exec' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'exec' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testfloat1.py": {
      "identifier": "original/k-python/programs/testfloat1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testexec2.py": {
      "identifier": "original/k-python/programs/testexec2.py",
      "stdout": "",
      "stderr": "exception: name 'exec' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'exec' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testfor2.py": {
      "identifier": "original/k-python/programs/testfor2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfor1.py": {
      "identifier": "original/k-python/programs/testfor1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testexceptions1.py": {
      "identifier": "original/k-python/programs/testexceptions1.py",
      "stdout": "",
      "stderr": "TypeError: unexpected keyword argument(s): {name: 4, path: 5}\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " unexpected keyword argument(s): {name: 4, path: 5}",
      "timeout": false
    },
    "original/k-python/programs/testformat1.py": {
      "identifier": "original/k-python/programs/testformat1.py",
      "stdout": "",
      "stderr": "exception: name 'format' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'format' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testfor3.py": {
      "identifier": "original/k-python/programs/testfor3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfor4.py": {
      "identifier": "original/k-python/programs/testfor4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testformat2.py": {
      "identifier": "original/k-python/programs/testformat2.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testformat3.py": {
      "identifier": "original/k-python/programs/testformat3.py",
      "stdout": "",
      "stderr": "exception: name 'format' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'format' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testformat4.py": {
      "identifier": "original/k-python/programs/testformat4.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute format\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute format",
      "timeout": false
    },
    "original/k-python/programs/testformat5.py": {
      "identifier": "original/k-python/programs/testformat5.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testfuncfinally1.py": {
      "identifier": "original/k-python/programs/testfuncfinally1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfuncfinally2.py": {
      "identifier": "original/k-python/programs/testfuncfinally2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfuncfinally3.py": {
      "identifier": "original/k-python/programs/testfuncfinally3.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfuncfinally4.py": {
      "identifier": "original/k-python/programs/testfuncfinally4.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testfuncraise2.py": {
      "identifier": "original/k-python/programs/testfuncraise2.py",
      "stdout": "",
      "stderr": "exception: name 'x' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'x' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testfunctions1.py": {
      "identifier": "original/k-python/programs/testfunctions1.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testfunctions10.py": {
      "identifier": "original/k-python/programs/testfunctions10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfuncraise1.py": {
      "identifier": "original/k-python/programs/testfuncraise1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions13.py": {
      "identifier": "original/k-python/programs/testfunctions13.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __module__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __module__",
      "timeout": false
    },
    "original/k-python/programs/testfunctions12.py": {
      "identifier": "original/k-python/programs/testfunctions12.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions2.py": {
      "identifier": "original/k-python/programs/testfunctions2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions14.py": {
      "identifier": "original/k-python/programs/testfunctions14.py",
      "stdout": "",
      "stderr": "ImportError: module types not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module types not found",
      "timeout": false
    },
    "original/k-python/programs/testfunctions7.py": {
      "identifier": "original/k-python/programs/testfunctions7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions8.py": {
      "identifier": "original/k-python/programs/testfunctions8.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions11.py": {
      "identifier": "original/k-python/programs/testfunctions11.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions6.py": {
      "identifier": "original/k-python/programs/testfunctions6.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testfunctions3.py": {
      "identifier": "original/k-python/programs/testfunctions3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testgetattr1.py": {
      "identifier": "original/k-python/programs/testgetattr1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testgetattr2.py": {
      "identifier": "original/k-python/programs/testgetattr2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testgetattr3.py": {
      "identifier": "original/k-python/programs/testgetattr3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testgetattr4.py": {
      "identifier": "original/k-python/programs/testgetattr4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testdicts1.py": {
      "identifier": "original/k-python/programs/testdicts1.py",
      "stdout": "",
      "stderr": "string-ref: index is out of range\n  index: 1\n  valid range: [0, 0]\n  string: \"7\"\n  context...:\n   /home/koehlma/lambda-py/base/builtins/str.rkt:148:0: str-getitem\n   prim-alloc\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:28:0: interp-cascade\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testgetattr5.py": {
      "identifier": "original/k-python/programs/testgetattr5.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testfunctions9.py": {
      "identifier": "original/k-python/programs/testfunctions9.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testimport2.py": {
      "identifier": "original/k-python/programs/testimport2.py",
      "stdout": "",
      "stderr": "exception raised by exception handler: gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.\n",
      "returncode": 1,
      "exception": "exception raised by exception handler",
      "message": " gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.",
      "timeout": false
    },
    "original/k-python/programs/testfunctions4.py": {
      "identifier": "original/k-python/programs/testfunctions4.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testif.py": {
      "identifier": "original/k-python/programs/testif.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testhash.py": {
      "identifier": "original/k-python/programs/testhash.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testimport4.py": {
      "identifier": "original/k-python/programs/testimport4.py",
      "stdout": "",
      "stderr": "string=?: contract violation\n  expected: string?\n  given: #\\nul\n  argument position: 2nd\n  other arguments...:\n   \"sys\"\n  context...:\n   /home/koehlma/lambda-py/base/builtins/str.rkt:79:0: streq\n   prim-noalloc\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 4 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testimport3.py": {
      "identifier": "original/k-python/programs/testimport3.py",
      "stdout": "",
      "stderr": "ImportError: module package1 not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module package1 not found",
      "timeout": false
    },
    "original/k-python/programs/testfunctions5.py": {
      "identifier": "original/k-python/programs/testfunctions5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testgetattr6.py": {
      "identifier": "original/k-python/programs/testgetattr6.py",
      "stdout": "",
      "stderr": "exception: name 'format' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'format' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testin.py": {
      "identifier": "original/k-python/programs/testin.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testimport1.py": {
      "identifier": "original/k-python/programs/testimport1.py",
      "stdout": "",
      "stderr": "ImportError: module module1 not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module module1 not found",
      "timeout": false
    },
    "original/k-python/programs/testintegers1.py": {
      "identifier": "original/k-python/programs/testintegers1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers3.py": {
      "identifier": "original/k-python/programs/testintegers3.py",
      "stdout": "",
      "stderr": "exception: class %type has no attribute __neg__\n",
      "returncode": 1,
      "exception": "exception",
      "message": " class %type has no attribute __neg__",
      "timeout": false
    },
    "original/k-python/programs/testintegers10.py": {
      "identifier": "original/k-python/programs/testintegers10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers5.py": {
      "identifier": "original/k-python/programs/testintegers5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers2.py": {
      "identifier": "original/k-python/programs/testintegers2.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __radd__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __radd__",
      "timeout": false
    },
    "original/k-python/programs/testintegers4.py": {
      "identifier": "original/k-python/programs/testintegers4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers6.py": {
      "identifier": "original/k-python/programs/testintegers6.py",
      "stdout": "",
      "stderr": "exception: Bad prim (alloc): num+ (5 5)\n",
      "returncode": 1,
      "exception": "exception",
      "message": " Bad prim (alloc): num+ (5 5)",
      "timeout": false
    },
    "original/k-python/programs/testio1.py": {
      "identifier": "original/k-python/programs/testio1.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 13, Column 24, Position 290):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b''\"))))\n  context...:\n   f1001\n   f822\n   loop\n   [repeats 3 more times]\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers8.py": {
      "identifier": "original/k-python/programs/testintegers8.py",
      "stdout": "",
      "stderr": "expt: undefined for 0 and -1\n  context...:\n   /home/koehlma/lambda-py/base/builtins/num.rkt:346:0: num**\n   prim-alloc\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 4 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:661:0: interp\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers7.py": {
      "identifier": "original/k-python/programs/testintegers7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testio5.py": {
      "identifier": "original/k-python/programs/testio5.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 4, Column 19, Position 97):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'abc\\\\ndef\\\\nghi\\\\n'\"))))\n  context...:\n   f1001\n   f822\n   loop\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testintegers9.py": {
      "identifier": "original/k-python/programs/testintegers9.py",
      "stdout": "",
      "stderr": "exception: name 'hash' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'hash' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testio3.py": {
      "identifier": "original/k-python/programs/testio3.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testio4.py": {
      "identifier": "original/k-python/programs/testio4.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testio2.py": {
      "identifier": "original/k-python/programs/testio2.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testio6.py": {
      "identifier": "original/k-python/programs/testio6.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testio7.py": {
      "identifier": "original/k-python/programs/testio7.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testio8.py": {
      "identifier": "original/k-python/programs/testio8.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testis.py": {
      "identifier": "original/k-python/programs/testis.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlambda.py": {
      "identifier": "original/k-python/programs/testlambda.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testiter1.py": {
      "identifier": "original/k-python/programs/testiter1.py",
      "stdout": "",
      "stderr": "exception: Arity mismatch: expected '(), received 7\n",
      "returncode": 1,
      "exception": "exception",
      "message": " Arity mismatch: expected '(), received 7",
      "timeout": false
    },
    "original/k-python/programs/testlen.py": {
      "identifier": "original/k-python/programs/testlen.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testisinstance2.py": {
      "identifier": "original/k-python/programs/testisinstance2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testiter2.py": {
      "identifier": "original/k-python/programs/testiter2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists1.py": {
      "identifier": "original/k-python/programs/testlists1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testissubclass2.py": {
      "identifier": "original/k-python/programs/testissubclass2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists10.py": {
      "identifier": "original/k-python/programs/testlists10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testisinstance1.py": {
      "identifier": "original/k-python/programs/testisinstance1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists11.py": {
      "identifier": "original/k-python/programs/testlists11.py",
      "stdout": "",
      "stderr": "util: list-replace out of range\n  context...:\n   /home/koehlma/lambda-py/base/util.rkt:92:0: list-replace\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/builtins/list.rkt:68:0: list-setitem\n   prim-update\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   /home/koehlma/lambda-py/base/python-interp.rkt:661:0: interp\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists3.py": {
      "identifier": "original/k-python/programs/testlists3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testlists2.py": {
      "identifier": "original/k-python/programs/testlists2.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists4.py": {
      "identifier": "original/k-python/programs/testlists4.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testlists5.py": {
      "identifier": "original/k-python/programs/testlists5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists6.py": {
      "identifier": "original/k-python/programs/testlists6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testissubclass1.py": {
      "identifier": "original/k-python/programs/testissubclass1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists7.py": {
      "identifier": "original/k-python/programs/testlists7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testlists9.py": {
      "identifier": "original/k-python/programs/testlists9.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally1.py": {
      "identifier": "original/k-python/programs/testloopfinally1.py",
      "stdout": "",
      "stderr": "exception: name 'z' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'z' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testlists8.py": {
      "identifier": "original/k-python/programs/testlists8.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally5.py": {
      "identifier": "original/k-python/programs/testloopfinally5.py",
      "stdout": "",
      "stderr": "exception: name 'z' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'z' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally2.py": {
      "identifier": "original/k-python/programs/testloopfinally2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally4.py": {
      "identifier": "original/k-python/programs/testloopfinally4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally3.py": {
      "identifier": "original/k-python/programs/testloopfinally3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally6.py": {
      "identifier": "original/k-python/programs/testloopfinally6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally9.py": {
      "identifier": "original/k-python/programs/testloopfinally9.py",
      "stdout": "",
      "stderr": "exception: reraise previous exception if possible\n",
      "returncode": 1,
      "exception": "exception",
      "message": " reraise previous exception if possible",
      "timeout": false
    },
    "original/k-python/programs/testmockimport1.py": {
      "identifier": "original/k-python/programs/testmockimport1.py",
      "stdout": "",
      "stderr": "exception raised by exception handler: gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.\n",
      "returncode": 1,
      "exception": "exception raised by exception handler",
      "message": " gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.",
      "timeout": false
    },
    "original/k-python/programs/testmockimport2.py": {
      "identifier": "original/k-python/programs/testmockimport2.py",
      "stdout": "",
      "stderr": "exception raised by exception handler: gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.\n",
      "returncode": 1,
      "exception": "exception raised by exception handler",
      "message": " gen-recur: (exn:plai \"desugar: star expression is not allowed yet.\" #<continuation-mark-set>); original exception raised: desugar: star expression is not allowed yet.",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally7.py": {
      "identifier": "original/k-python/programs/testloopfinally7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testmap.py": {
      "identifier": "original/k-python/programs/testmap.py",
      "stdout": "",
      "stderr": "exception: name 'map' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'map' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testloopfinally8.py": {
      "identifier": "original/k-python/programs/testloopfinally8.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testnone.py": {
      "identifier": "original/k-python/programs/testnone.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __ne__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __ne__",
      "timeout": false
    },
    "original/k-python/programs/testmodule1.py": {
      "identifier": "original/k-python/programs/testmodule1.py",
      "stdout": "",
      "stderr": "ImportError: module _io not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _io not found",
      "timeout": false
    },
    "original/k-python/programs/testposix3.py": {
      "identifier": "original/k-python/programs/testposix3.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 7, Column 19, Position 126):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'programs/files'\"))))\n  context...:\n   f1087\n   f860\n   loop\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testmockimport4.py": {
      "identifier": "original/k-python/programs/testmockimport4.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testobject2.py": {
      "identifier": "original/k-python/programs/testobject2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testmockimport3.py": {
      "identifier": "original/k-python/programs/testmockimport3.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testord.py": {
      "identifier": "original/k-python/programs/testord.py",
      "stdout": "",
      "stderr": "exception: name 'ord' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'ord' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testobject3.py": {
      "identifier": "original/k-python/programs/testobject3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testmockimport5.py": {
      "identifier": "original/k-python/programs/testmockimport5.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testpass.py": {
      "identifier": "original/k-python/programs/testpass.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testobject4.py": {
      "identifier": "original/k-python/programs/testobject4.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testposix2.py": {
      "identifier": "original/k-python/programs/testposix2.py",
      "stdout": "",
      "stderr": "ImportError: module posix not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module posix not found",
      "timeout": false
    },
    "original/k-python/programs/testobject1.py": {
      "identifier": "original/k-python/programs/testobject1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testrepr1.py": {
      "identifier": "original/k-python/programs/testrepr1.py",
      "stdout": "",
      "stderr": "exception: name 'repr' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'repr' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testposix1.py": {
      "identifier": "original/k-python/programs/testposix1.py",
      "stdout": "",
      "stderr": "ImportError: module posix not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module posix not found",
      "timeout": false
    },
    "original/k-python/programs/testreversed1.py": {
      "identifier": "original/k-python/programs/testreversed1.py",
      "stdout": "",
      "stderr": "exception: name 'reversed' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'reversed' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testscope1.py": {
      "identifier": "original/k-python/programs/testscope1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testrepr2.py": {
      "identifier": "original/k-python/programs/testrepr2.py",
      "stdout": "",
      "stderr": "exception: name 'repr' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'repr' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testreversed2.py": {
      "identifier": "original/k-python/programs/testreversed2.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testscope11.py": {
      "identifier": "original/k-python/programs/testscope11.py",
      "stdout": "",
      "stderr": "exception: name '__class__' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name '__class__' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testscope10.py": {
      "identifier": "original/k-python/programs/testscope10.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute baz\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute baz",
      "timeout": false
    },
    "original/k-python/programs/testscope3.py": {
      "identifier": "original/k-python/programs/testscope3.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __code__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __code__",
      "timeout": false
    },
    "original/k-python/programs/testscope6.py": {
      "identifier": "original/k-python/programs/testscope6.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __code__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __code__",
      "timeout": false
    },
    "original/k-python/programs/testscope12.py": {
      "identifier": "original/k-python/programs/testscope12.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute f_code\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute f_code",
      "timeout": false
    },
    "original/k-python/programs/testscope2.py": {
      "identifier": "original/k-python/programs/testscope2.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __code__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __code__",
      "timeout": false
    },
    "original/k-python/programs/testscope5.py": {
      "identifier": "original/k-python/programs/testscope5.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __code__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __code__",
      "timeout": false
    },
    "original/k-python/programs/testscope4.py": {
      "identifier": "original/k-python/programs/testscope4.py",
      "stdout": "",
      "stderr": "AttributeError: function object has not attribute __code__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " function object has not attribute __code__",
      "timeout": false
    },
    "original/k-python/programs/testscope8.py": {
      "identifier": "original/k-python/programs/testscope8.py",
      "stdout": "",
      "stderr": "exception: name 'y' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'y' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testscope9.py": {
      "identifier": "original/k-python/programs/testscope9.py",
      "stdout": "",
      "stderr": "exception: name '__class__' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name '__class__' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testscope7.py": {
      "identifier": "original/k-python/programs/testscope7.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testrange.py": {
      "identifier": "original/k-python/programs/testrange.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsetattr2.py": {
      "identifier": "original/k-python/programs/testsetattr2.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testsetattr3.py": {
      "identifier": "original/k-python/programs/testsetattr3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testsetattr1.py": {
      "identifier": "original/k-python/programs/testsetattr1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsetattr4.py": {
      "identifier": "original/k-python/programs/testsetattr4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsetattr5.py": {
      "identifier": "original/k-python/programs/testsetattr5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststaticmethod.py": {
      "identifier": "original/k-python/programs/teststaticmethod.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststrings1.py": {
      "identifier": "original/k-python/programs/teststrings1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsetattr6.py": {
      "identifier": "original/k-python/programs/testsetattr6.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststrings10.py": {
      "identifier": "original/k-python/programs/teststrings10.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsets.py": {
      "identifier": "original/k-python/programs/testsets.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testslice.py": {
      "identifier": "original/k-python/programs/testslice.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __slice__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __slice__",
      "timeout": false
    },
    "original/k-python/programs/teststrings2.py": {
      "identifier": "original/k-python/programs/teststrings2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststrings3.py": {
      "identifier": "original/k-python/programs/teststrings3.py",
      "stdout": "",
      "stderr": "exception: class %type has no attribute __name__\n",
      "returncode": 1,
      "exception": "exception",
      "message": " class %type has no attribute __name__",
      "timeout": false
    },
    "original/k-python/programs/teststrings5.py": {
      "identifier": "original/k-python/programs/teststrings5.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute rsplit\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute rsplit",
      "timeout": false
    },
    "original/k-python/programs/teststrings11.py": {
      "identifier": "original/k-python/programs/teststrings11.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststrings7.py": {
      "identifier": "original/k-python/programs/teststrings7.py",
      "stdout": "",
      "stderr": "string-ref: contract violation\n  expected: exact-nonnegative-integer?\n  given: -1\n  argument position: 2nd\n  other arguments...:\n   \"12345\"\n  context...:\n   /home/koehlma/lambda-py/base/builtins/str.rkt:148:0: str-getitem\n   prim-alloc\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:28:0: interp-cascade\n   /home/koehlma/lambda-py/base/python-interp.rkt:44:0: interp-capp\n   /home/koehlma/lambda-py/base/python-interp.rkt:196:0: interp-env\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-interp.rkt:661:0: interp\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/teststrings4.py": {
      "identifier": "original/k-python/programs/teststrings4.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute rpartition\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute rpartition",
      "timeout": false
    },
    "original/k-python/programs/teststrings6.py": {
      "identifier": "original/k-python/programs/teststrings6.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute startswith\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute startswith",
      "timeout": false
    },
    "original/k-python/programs/teststrings8.py": {
      "identifier": "original/k-python/programs/teststrings8.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute join\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute join",
      "timeout": false
    },
    "original/k-python/programs/teststrings9.py": {
      "identifier": "original/k-python/programs/teststrings9.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute partition\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute partition",
      "timeout": false
    },
    "original/k-python/programs/testsuper2.py": {
      "identifier": "original/k-python/programs/testsuper2.py",
      "stdout": "",
      "stderr": "exception: name 'x' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'x' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testsuper4.py": {
      "identifier": "original/k-python/programs/testsuper4.py",
      "stdout": "",
      "stderr": "SyntaxError: no binding for nonlocal '__class__' found\n",
      "returncode": 1,
      "exception": "SyntaxError",
      "message": " no binding for nonlocal '__class__' found",
      "timeout": false
    },
    "original/k-python/programs/testtry1.py": {
      "identifier": "original/k-python/programs/testtry1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsuper3.py": {
      "identifier": "original/k-python/programs/testsuper3.py",
      "stdout": "",
      "stderr": "exception: name '__class__' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name '__class__' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testtry11.py": {
      "identifier": "original/k-python/programs/testtry11.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testsuper5.py": {
      "identifier": "original/k-python/programs/testsuper5.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry14.py": {
      "identifier": "original/k-python/programs/testtry14.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsys.py": {
      "identifier": "original/k-python/programs/testsys.py",
      "stdout": "",
      "stderr": "AssertionError: .\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": " .",
      "timeout": false
    },
    "original/k-python/programs/testtry10.py": {
      "identifier": "original/k-python/programs/testtry10.py",
      "stdout": "",
      "stderr": "exception: name 'y' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'y' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testtry13.py": {
      "identifier": "original/k-python/programs/testtry13.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __suppress_context__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __suppress_context__",
      "timeout": false
    },
    "original/k-python/programs/testtry15.py": {
      "identifier": "original/k-python/programs/testtry15.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry12.py": {
      "identifier": "original/k-python/programs/testtry12.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry2.py": {
      "identifier": "original/k-python/programs/testtry2.py",
      "stdout": "",
      "stderr": "exception: name 'x' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'x' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testtry4.py": {
      "identifier": "original/k-python/programs/testtry4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry3.py": {
      "identifier": "original/k-python/programs/testtry3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testtry6.py": {
      "identifier": "original/k-python/programs/testtry6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry5.py": {
      "identifier": "original/k-python/programs/testtry5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtry7.py": {
      "identifier": "original/k-python/programs/testtry7.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples10.py": {
      "identifier": "original/k-python/programs/testtuples10.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testtuples12.py": {
      "identifier": "original/k-python/programs/testtuples12.py",
      "stdout": "",
      "stderr": "exception: name 'hash' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'hash' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testtry8.py": {
      "identifier": "original/k-python/programs/testtry8.py",
      "stdout": "",
      "stderr": "exception: name 'y' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'y' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testtry9.py": {
      "identifier": "original/k-python/programs/testtry9.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __cause__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __cause__",
      "timeout": false
    },
    "original/k-python/programs/testtuples1.py": {
      "identifier": "original/k-python/programs/testtuples1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples5.py": {
      "identifier": "original/k-python/programs/testtuples5.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __context__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __context__",
      "timeout": false
    },
    "original/k-python/programs/testtuples11.py": {
      "identifier": "original/k-python/programs/testtuples11.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples2.py": {
      "identifier": "original/k-python/programs/testtuples2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples3.py": {
      "identifier": "original/k-python/programs/testtuples3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples4.py": {
      "identifier": "original/k-python/programs/testtuples4.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __context__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __context__",
      "timeout": false
    },
    "original/k-python/programs/testtuples6.py": {
      "identifier": "original/k-python/programs/testtuples6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples7.py": {
      "identifier": "original/k-python/programs/testtuples7.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testtuples9.py": {
      "identifier": "original/k-python/programs/testtuples9.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testtuples8.py": {
      "identifier": "original/k-python/programs/testtuples8.py",
      "stdout": "",
      "stderr": "exception: name 'x' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'x' is not defined",
      "timeout": false
    },
    "original/k-python/programs/testwhile3.py": {
      "identifier": "original/k-python/programs/testwhile3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testweakref.py": {
      "identifier": "original/k-python/programs/testweakref.py",
      "stdout": "",
      "stderr": "ImportError: module _weakref not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module _weakref not found",
      "timeout": false
    },
    "original/k-python/programs/testwhile1.py": {
      "identifier": "original/k-python/programs/testwhile1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testwhile4.py": {
      "identifier": "original/k-python/programs/testwhile4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testwhile2.py": {
      "identifier": "original/k-python/programs/testwhile2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testwith2.py": {
      "identifier": "original/k-python/programs/testwith2.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testwith1.py": {
      "identifier": "original/k-python/programs/testwith1.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield1.py": {
      "identifier": "original/k-python/programs/testyield1.py",
      "stdout": "",
      "stderr": "exception: Bad prim (noalloc): obj-getattr (5 __func__)\n",
      "returncode": 1,
      "exception": "exception",
      "message": " Bad prim (noalloc): obj-getattr (5 __func__)",
      "timeout": false
    },
    "original/k-python/programs/testwith4.py": {
      "identifier": "original/k-python/programs/testwith4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield10.py": {
      "identifier": "original/k-python/programs/testyield10.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testwith3.py": {
      "identifier": "original/k-python/programs/testwith3.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testyield11.py": {
      "identifier": "original/k-python/programs/testyield11.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield12.py": {
      "identifier": "original/k-python/programs/testyield12.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield13.py": {
      "identifier": "original/k-python/programs/testyield13.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute throw\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute throw",
      "timeout": false
    },
    "original/k-python/programs/testyield14.py": {
      "identifier": "original/k-python/programs/testyield14.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testyield3.py": {
      "identifier": "original/k-python/programs/testyield3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield2.py": {
      "identifier": "original/k-python/programs/testyield2.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute throw\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute throw",
      "timeout": false
    },
    "original/k-python/programs/testyield4.py": {
      "identifier": "original/k-python/programs/testyield4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield6.py": {
      "identifier": "original/k-python/programs/testyield6.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield9.py": {
      "identifier": "original/k-python/programs/testyield9.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute close\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute close",
      "timeout": false
    },
    "original/k-python/programs/testyield5.py": {
      "identifier": "original/k-python/programs/testyield5.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testyield8.py": {
      "identifier": "original/k-python/programs/testyield8.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/k-python/programs/testyield7.py": {
      "identifier": "original/k-python/programs/testyield7.py",
      "stdout": "",
      "stderr": "exception: name 'x' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'x' is not defined",
      "timeout": false
    },
    "original/lambda-py/generators/send-gen.py": {
      "identifier": "original/lambda-py/generators/send-gen.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute __add__\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute __add__",
      "timeout": false
    },
    "original/lambda-py/generators/gen-except.py": {
      "identifier": "original/lambda-py/generators/gen-except.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/lambda-py/modules/support_exception.py": {
      "identifier": "original/lambda-py/modules/support_exception.py",
      "stdout": "",
      "stderr": "TypeError\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/bugs/methodinstance.py": {
      "identifier": "original/lambda-py/bugs/methodinstance.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/bugs/setitem.py": {
      "identifier": "original/lambda-py/bugs/setitem.py",
      "stdout": "",
      "stderr": "exception: Bad prim (noalloc): obj-getattr (<function> __func__)\n",
      "returncode": 1,
      "exception": "exception",
      "message": " Bad prim (noalloc): obj-getattr (<function> __func__)",
      "timeout": false
    },
    "original/lambda-py/generators/gen-method.py": {
      "identifier": "original/lambda-py/generators/gen-method.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute throw\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute throw",
      "timeout": false
    },
    "original/lambda-py/modules/test_exception.py": {
      "identifier": "original/lambda-py/modules/test_exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/test_import_name_binding.py": {
      "identifier": "original/lambda-py/modules/test_import_name_binding.py",
      "stdout": "",
      "stderr": "ImportError: module test_as not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module test_as not found",
      "timeout": false
    },
    "original/lambda-py/modules/test_meta_path.py": {
      "identifier": "original/lambda-py/modules/test_meta_path.py",
      "stdout": "",
      "stderr": "AttributeError: object has no attribute meta_path\n",
      "returncode": 1,
      "exception": "AttributeError",
      "message": " object has no attribute meta_path",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_builtin.py": {
      "identifier": "original/lambda-py/modules/unittest/test_builtin.py",
      "stdout": "",
      "stderr": "integer->char: contract violation\n  expected: (and/c (integer-in 0 #x10FFFF) (not/c (integer-in #xD800 #xDFFF)))\n  given: 55296\n  context...:\n   f115\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:95:0: backslash-escaped\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:194:2: continue-string271\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:362:11: slurg\n   /usr/share/racket/collects/racket/generator.rkt:93:4: cont\n",
      "returncode": 1,
      "exception": "/usr/share/racket/collects/racket/generator.rkt",
      "message": "93:4: cont",
      "timeout": false
    },
    "original/lambda-py/modules/test_as/__init__.py": {
      "identifier": "original/lambda-py/modules/test_as/__init__.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/test_as/empty.py": {
      "identifier": "original/lambda-py/modules/test_as/empty.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/test_unary.py": {
      "identifier": "original/lambda-py/modules/test_unary.py",
      "stdout": "",
      "stderr": "exact?: contract violation\n  expected: number?\n  given: '#hasheq((nodetype . \"Complex\") (value . \"2j\"))\n  context...:\n   /home/koehlma/lambda-py/base/util.rkt:445:0: make-builtin-num\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 5 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/test_with_extension.py": {
      "identifier": "original/lambda-py/modules/test_with_extension.py",
      "stdout": "",
      "stderr": "ImportError: module support not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module support not found",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_float.py": {
      "identifier": "original/lambda-py/modules/unittest/test_float.py",
      "stdout": "",
      "stderr": "integer->char: contract violation\n  expected: (and/c (integer-in 0 #x10FFFF) (not/c (integer-in #xD800 #xDFFF)))\n  given: 55536\n  context...:\n   f115\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:95:0: backslash-escaped\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:194:2: continue-string271\n   /home/koehlma/lambda-py/base/parser/python-lexer.rkt:362:11: slurg\n   /usr/share/racket/collects/racket/generator.rkt:93:4: cont\n",
      "returncode": 1,
      "exception": "/usr/share/racket/collects/racket/generator.rkt",
      "message": "93:4: cont",
      "timeout": false
    },
    "original/lambda-py/generators/gen-comp.py": {
      "identifier": "original/lambda-py/generators/gen-comp.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_bool.py": {
      "identifier": "original/lambda-py/modules/unittest/test_bool.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 280, Column 57, Position 9854):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'I01\\\\n.'\"))))\n  context...:\n   f1087\n   parse-loop54\n   f682\n   loop\n   [repeats 6 more times]\n   parse-loop54\n   f716\n   loop\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_file.py": {
      "identifier": "original/lambda-py/modules/unittest/test_file.py",
      "stdout": "",
      "stderr": "ImportError: module random not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module random not found",
      "timeout": false
    },
    "original/lambda-py/multiple_inheritance/super-external-self.py": {
      "identifier": "original/lambda-py/multiple_inheritance/super-external-self.py",
      "stdout": "",
      "stderr": "exception: name 'SystemError' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'SystemError' is not defined",
      "timeout": false
    },
    "original/lambda-py/multiple_inheritance/super-external.py": {
      "identifier": "original/lambda-py/multiple_inheritance/super-external.py",
      "stdout": "",
      "stderr": "exception: name 'SystemError' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'SystemError' is not defined",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_unary.py": {
      "identifier": "original/lambda-py/modules/unittest/test_unary.py",
      "stdout": "",
      "stderr": "exact?: contract violation\n  expected: number?\n  given: '#hasheq((nodetype . \"Complex\") (value . \"2j\"))\n  context...:\n   /home/koehlma/lambda-py/base/util.rkt:445:0: make-builtin-num\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 5 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_list.py": {
      "identifier": "original/lambda-py/modules/unittest/test_list.py",
      "stdout": "",
      "stderr": "ImportError: module test not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module test not found",
      "timeout": false
    },
    "original/lambda-py/multiple_inheritance/super-nested-not-self.py": {
      "identifier": "original/lambda-py/multiple_inheritance/super-nested-not-self.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/multiple_inheritance/super-nested-noarg.py": {
      "identifier": "original/lambda-py/multiple_inheritance/super-nested-noarg.py",
      "stdout": "",
      "stderr": "exception: name 'SystemError' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name 'SystemError' is not defined",
      "timeout": false
    },
    "original/lambda-py/multiple_inheritance/super-nested-self.py": {
      "identifier": "original/lambda-py/multiple_inheritance/super-nested-self.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_string.py": {
      "identifier": "original/lambda-py/modules/unittest/test_string.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/parser/parser-regress.py": {
      "identifier": "original/lambda-py/parser/parser-regress.py",
      "stdout": "",
      "stderr": "parse: Haven't handled a case yet (Line 32, Column 4, Position 491):\n'#hasheq((nodetype . \"Bytes\")\n         (s . #hasheq((nodetype . \"Bytes\") (value . \"b'helloworld'\"))))\n  context...:\n   loop\n   [repeats 5 more times]\n   parse-loop54\n   f682\n   f1135\n   /home/koehlma/lambda-py/base/python-tools.rkt:30:0: run-python\n   /usr/share/racket/collects/racket/cmdline.rkt:464:10: call-handler\n   \"/home/koehlma/lambda-py/base/python-main.rkt\": [running body]\n   temp37_0\n   for-loop\n   run-module-instance!125\n   perform-require!78\n",
      "returncode": 1,
      "exception": "perform-require!78",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_isinstance.py": {
      "identifier": "original/lambda-py/modules/unittest/test_isinstance.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-compare.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-compare.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_dictviews.py": {
      "identifier": "original/lambda-py/modules/unittest/test_dictviews.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_raise.py": {
      "identifier": "original/lambda-py/modules/unittest/test_raise.py",
      "stdout": "",
      "stderr": "ImportError: module test not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module test not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-callable.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-callable.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_augassign.py": {
      "identifier": "original/lambda-py/modules/unittest/test_augassign.py",
      "stdout": "",
      "stderr": "desugar: Shouldn't desugar slice directly\n  context...:\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 6 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 1 more time]\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-isinstance.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-isinstance.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-compare-list-dict.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-compare-list-dict.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-float.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-float.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-convert.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-convert.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-int.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-int.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_binop.py": {
      "identifier": "original/lambda-py/modules/unittest/test_binop.py",
      "stdout": "",
      "stderr": "exact?: contract violation\n  expected: number?\n  given: '#hasheq((nodetype . \"Complex\") (value . \"0j\"))\n  context...:\n   /home/koehlma/lambda-py/base/util.rkt:445:0: make-builtin-num\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 5 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 1 more time]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   [repeats 2 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   [repeats 8 more times]\n   /home/koehlma/lambda-py/base/python-desugar.rkt:144:0: desugar-seq\n   /home/koehlma/lambda-py/base/python-desugar.rkt:276:0: rec-desugar\n   ...\n",
      "returncode": 1,
      "exception": "...",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-math.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-math.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/bool/bool-str.py": {
      "identifier": "original/lambda-py/python-reference/bool/bool-str.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/callable.py": {
      "identifier": "original/lambda-py/python-reference/builtin/callable.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_int.py": {
      "identifier": "original/lambda-py/modules/unittest/test_int.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/any.py": {
      "identifier": "original/lambda-py/python-reference/builtin/any.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/property/lambda_getter.py": {
      "identifier": "original/lambda-py/property/lambda_getter.py",
      "stdout": "",
      "stderr": "TypeError: unexpected keyword argument(s): {doc: spam spam spam}\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " unexpected keyword argument(s): {doc: spam spam spam}",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/all.py": {
      "identifier": "original/lambda-py/python-reference/builtin/all.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/isinstance.py": {
      "identifier": "original/lambda-py/python-reference/builtin/isinstance.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/isinstance-tuple.py": {
      "identifier": "original/lambda-py/python-reference/builtin/isinstance-tuple.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/class-decorators.py": {
      "identifier": "original/lambda-py/python-reference/class/class-decorators.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/len.py": {
      "identifier": "original/lambda-py/python-reference/builtin/len.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/property/base.py": {
      "identifier": "original/lambda-py/property/base.py",
      "stdout": "",
      "stderr": "TypeError: unexpected keyword argument(s): {doc: spam spam spam}\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " unexpected keyword argument(s): {doc: spam spam spam}",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/filter.py": {
      "identifier": "original/lambda-py/python-reference/builtin/filter.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/test_class_dict.py": {
      "identifier": "original/lambda-py/python-reference/class/test_class_dict.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-bool.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-bool.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-attribute.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-attribute.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/metaclass-class2.py": {
      "identifier": "original/lambda-py/python-reference/class/metaclass-class2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-get.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-get.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-contains.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-contains.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/metaclass-class1.py": {
      "identifier": "original/lambda-py/python-reference/class/metaclass-class1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/metaclass-function.py": {
      "identifier": "original/lambda-py/python-reference/class/metaclass-function.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-clear.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-clear.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-hash-effects.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-hash-effects.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-items.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-items.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-keys-effects.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-keys-effects.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-getitem.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-getitem.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-keys.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-keys.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/metaclass-class3.py": {
      "identifier": "original/lambda-py/python-reference/class/metaclass-class3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-list.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-list.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_scope.py": {
      "identifier": "original/lambda-py/modules/unittest/test_scope.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/assert-silent.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/assert-silent.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/test-dict-aug-assign.py": {
      "identifier": "original/lambda-py/python-reference/dict/test-dict-aug-assign.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/assertion-error-msg.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/assertion-error-msg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_types.py": {
      "identifier": "original/lambda-py/modules/unittest/test_types.py",
      "stdout": "",
      "stderr": "ImportError: module test.support not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module test.support not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-set-comprehensions.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-set-comprehensions.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/assertion-error.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/assertion-error.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-values.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-values.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/elseReturn.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/elseReturn.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/assertRaises.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/assertRaises.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/except-reraise.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/except-reraise.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/invalid-reraise.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/invalid-reraise.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/nested-reraise.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/nested-reraise.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/except-as.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/except-as.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/class/test_metaclass.py": {
      "identifier": "original/lambda-py/python-reference/class/test_metaclass.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-update-iterable.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-update-iterable.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/nested-else.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/nested-else.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/nested.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/nested.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/reraise.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/reraise.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/test-try-except-no-exception.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/test-try-except-no-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/test-try-except-else.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/test-try-except-else.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/test-finally-reraise.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/test-finally-reraise.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-set-keys.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-set-keys.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-except-else-finally-no-exception.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-except-else-finally-no-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/test-try-except.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/test-try-except.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-except-else-finally.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-except-else-finally.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/test_with.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/test_with.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-except-else-no-exception.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-except-else-no-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-except-finally-no-exception.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-except-finally-no-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-values-set.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-values-set.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-except-finally.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-except-finally.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/try-finally-no-exception.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/try-finally-no-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/dict/dict-update.py": {
      "identifier": "original/lambda-py/python-reference/dict/dict-update.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/func_attr.py": {
      "identifier": "original/lambda-py/python-reference/functions/func_attr.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/func_attr2.py": {
      "identifier": "original/lambda-py/python-reference/functions/func_attr2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/while-break-finally.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/while-break-finally.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/exceptions/while-continue-finally.py": {
      "identifier": "original/lambda-py/python-reference/exceptions/while-continue-finally.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/modules/unittest/test_dict.py": {
      "identifier": "original/lambda-py/modules/unittest/test_dict.py",
      "stdout": "",
      "stderr": "ImportError: module unittest not found\n",
      "returncode": 1,
      "exception": "ImportError",
      "message": " module unittest not found",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/non_tuple_starag.py": {
      "identifier": "original/lambda-py/python-reference/functions/non_tuple_starag.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/varargs.py": {
      "identifier": "original/lambda-py/python-reference/functions/varargs.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-arg.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-arg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/basic-gen.py": {
      "identifier": "original/lambda-py/python-reference/generators/basic-gen.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-exception.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-exception.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-in-gen.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-in-gen.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/func_defaults.py": {
      "identifier": "original/lambda-py/python-reference/functions/func_defaults.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-list.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-list.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/lambda_defaults.py": {
      "identifier": "original/lambda-py/python-reference/functions/lambda_defaults.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-return-uncatchable.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-return-uncatchable.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-multiyield.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-multiyield.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/kwonlyargs.py": {
      "identifier": "original/lambda-py/python-reference/functions/kwonlyargs.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/lambda_stararg.py": {
      "identifier": "original/lambda-py/python-reference/functions/lambda_stararg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/gen-return.py": {
      "identifier": "original/lambda-py/python-reference/generators/gen-return.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/continue.py": {
      "identifier": "original/lambda-py/python-reference/iter/continue.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/func_stararg.py": {
      "identifier": "original/lambda-py/python-reference/functions/func_stararg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/generators/simple-gen.py": {
      "identifier": "original/lambda-py/python-reference/generators/simple-gen.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/test-for-else.py": {
      "identifier": "original/lambda-py/python-reference/iter/test-for-else.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/kwarg.py": {
      "identifier": "original/lambda-py/python-reference/functions/kwarg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/keywords_args3.py": {
      "identifier": "original/lambda-py/python-reference/functions/keywords_args3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/filter-comprehension.py": {
      "identifier": "original/lambda-py/python-reference/iter/filter-comprehension.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/iter-classes.py": {
      "identifier": "original/lambda-py/python-reference/iter/iter-classes.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/simple-append.py": {
      "identifier": "original/lambda-py/python-reference/lists/simple-append.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/iter-simple.py": {
      "identifier": "original/lambda-py/python-reference/iter/iter-simple.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/test-genexp-lazyness.py": {
      "identifier": "original/lambda-py/python-reference/iter/test-genexp-lazyness.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/test_list_assign.py": {
      "identifier": "original/lambda-py/python-reference/lists/test_list_assign.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/keywords_args4.py": {
      "identifier": "original/lambda-py/python-reference/functions/keywords_args4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/memofib-function-attributes.py": {
      "identifier": "original/lambda-py/python-reference/functions/memofib-function-attributes.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/simple-extend.py": {
      "identifier": "original/lambda-py/python-reference/lists/simple-extend.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/keywords_args1.py": {
      "identifier": "original/lambda-py/python-reference/functions/keywords_args1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/test_list_identity.py": {
      "identifier": "original/lambda-py/python-reference/lists/test_list_identity.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/iter-comprehensions.py": {
      "identifier": "original/lambda-py/python-reference/iter/iter-comprehensions.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/builtin/get_set_attribute.py": {
      "identifier": "original/lambda-py/python-reference/builtin/get_set_attribute.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/support.py": {
      "identifier": "original/lambda-py/python-reference/modules/support.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/test_list_truth.py": {
      "identifier": "original/lambda-py/python-reference/lists/test_list_truth.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/lists/test_list_simple.py": {
      "identifier": "original/lambda-py/python-reference/lists/test_list_simple.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/test_file.py": {
      "identifier": "original/lambda-py/python-reference/modules/test_file.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/test_in_modules.py": {
      "identifier": "original/lambda-py/python-reference/modules/test_in_modules.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/dunder-methods.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/dunder-methods.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/test_scope.py": {
      "identifier": "original/lambda-py/python-reference/modules/test_scope.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/test_basic.py": {
      "identifier": "original/lambda-py/python-reference/modules/test_basic.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test-classmethod-desugar.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test-classmethod-desugar.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/methods.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/methods.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test-staticmethod-decorator.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test-staticmethod-decorator.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/modules/test_failing_support_sticks.py": {
      "identifier": "original/lambda-py/python-reference/modules/test_failing_support_sticks.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test-staticmethod-oldstyle.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test-staticmethod-oldstyle.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_consistency_with_epg.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_consistency_with_epg.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_diamond_inheritence.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_diamond_inheritence.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_ex5_from_c3_switch.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_ex5_from_c3_switch.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_mro_disagreement.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_mro_disagreement.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/functions/keywords_args2.py": {
      "identifier": "original/lambda-py/python-reference/functions/keywords_args2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_monotonicity.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_monotonicity.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_mro_disagreement_type.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_mro_disagreement_type.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/shadow.py": {
      "identifier": "original/lambda-py/python-reference/property/shadow.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/override_getattr_descr.py": {
      "identifier": "original/lambda-py/python-reference/property/override_getattr_descr.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/type-dict.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/type-dict.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/iter-misc.py": {
      "identifier": "original/lambda-py/python-reference/iter/iter-misc.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/simple_getter.py": {
      "identifier": "original/lambda-py/python-reference/property/simple_getter.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_multiple_inheritance.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_multiple_inheritance.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/simple_getter_exn.py": {
      "identifier": "original/lambda-py/python-reference/property/simple_getter_exn.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/simple_property.py": {
      "identifier": "original/lambda-py/python-reference/property/simple_property.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/bound-and-free.py": {
      "identifier": "original/lambda-py/python-reference/scope/bound-and-free.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/range/slice1.py": {
      "identifier": "original/lambda-py/python-reference/range/slice1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/range/test-range-lazyness.py": {
      "identifier": "original/lambda-py/python-reference/range/test-range-lazyness.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/simple_property_decorator.py": {
      "identifier": "original/lambda-py/python-reference/property/simple_property_decorator.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/class-bases-scope.py": {
      "identifier": "original/lambda-py/python-reference/scope/class-bases-scope.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/multiple-inheritance/test_super_multiple_inheritance.py": {
      "identifier": "original/lambda-py/python-reference/multiple-inheritance/test_super_multiple_inheritance.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/range/range-list.py": {
      "identifier": "original/lambda-py/python-reference/range/range-list.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/test_property_decorator_baseclass.py": {
      "identifier": "original/lambda-py/python-reference/property/test_property_decorator_baseclass.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/comprehensions-leak.py": {
      "identifier": "original/lambda-py/python-reference/scope/comprehensions-leak.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/range/range-errs.py": {
      "identifier": "original/lambda-py/python-reference/range/range-errs.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/extra-nesting.py": {
      "identifier": "original/lambda-py/python-reference/scope/extra-nesting.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/destructuring-bind.py": {
      "identifier": "original/lambda-py/python-reference/scope/destructuring-bind.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/test_property_decorator_subclass.py": {
      "identifier": "original/lambda-py/python-reference/property/test_property_decorator_subclass.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/for-loops.py": {
      "identifier": "original/lambda-py/python-reference/scope/for-loops.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/range/range-vars.py": {
      "identifier": "original/lambda-py/python-reference/range/range-vars.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/global-in-parallel-nested-functions.py": {
      "identifier": "original/lambda-py/python-reference/scope/global-in-parallel-nested-functions.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/global_scope.py": {
      "identifier": "original/lambda-py/python-reference/scope/global_scope.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/global-in-class-body.py": {
      "identifier": "original/lambda-py/python-reference/scope/global-in-class-body.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/freevar-in-method.py": {
      "identifier": "original/lambda-py/python-reference/scope/freevar-in-method.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/lambda3.py": {
      "identifier": "original/lambda-py/python-reference/scope/lambda3.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/lambda1.py": {
      "identifier": "original/lambda-py/python-reference/scope/lambda1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/lambda4.py": {
      "identifier": "original/lambda-py/python-reference/scope/lambda4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/lambda2.py": {
      "identifier": "original/lambda-py/python-reference/scope/lambda2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/immutable-alias.py": {
      "identifier": "original/lambda-py/python-reference/scope/immutable-alias.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/property/test_property_getter_doc_override.py": {
      "identifier": "original/lambda-py/python-reference/property/test_property_getter_doc_override.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/locals-class.py": {
      "identifier": "original/lambda-py/python-reference/scope/locals-class.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nearest-enclosing-scope.py": {
      "identifier": "original/lambda-py/python-reference/scope/nearest-enclosing-scope.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/mixed-freevars-and-cellvars.py": {
      "identifier": "original/lambda-py/python-reference/scope/mixed-freevars-and-cellvars.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nested-classes.py": {
      "identifier": "original/lambda-py/python-reference/scope/nested-classes.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nesting-global-under-local.py": {
      "identifier": "original/lambda-py/python-reference/scope/nesting-global-under-local.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nested-nonlocal.py": {
      "identifier": "original/lambda-py/python-reference/scope/nested-nonlocal.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nesting-plus-free-ref-to-global.py": {
      "identifier": "original/lambda-py/python-reference/scope/nesting-plus-free-ref-to-global.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nesting-global-no-free.py": {
      "identifier": "original/lambda-py/python-reference/scope/nesting-global-no-free.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nesting-through-class.py": {
      "identifier": "original/lambda-py/python-reference/scope/nesting-through-class.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-class.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-class.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-function-vardef-shadow.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-function-vardef-shadow.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-function-vardef-unbound.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-function-vardef-unbound.py",
      "stdout": "",
      "stderr": "exception: local variable 'x' referenced before assignment\n",
      "returncode": 1,
      "exception": "exception",
      "message": " local variable 'x' referenced before assignment",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-function-vardef.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-function-vardef.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/iter/iter-stop.py": {
      "identifier": "original/lambda-py/python-reference/iter/iter-stop.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-function.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-function.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/recursion.py": {
      "identifier": "original/lambda-py/python-reference/scope/recursion.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/nonlocal-method.py": {
      "identifier": "original/lambda-py/python-reference/scope/nonlocal-method.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/simple-and-rebinding.py": {
      "identifier": "original/lambda-py/python-reference/scope/simple-and-rebinding.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/simple-nesting.py": {
      "identifier": "original/lambda-py/python-reference/scope/simple-nesting.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/locals-function.py": {
      "identifier": "original/lambda-py/python-reference/scope/locals-function.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/test-assign-field.py": {
      "identifier": "original/lambda-py/python-reference/scope/test-assign-field.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/locals-function-renamed.py": {
      "identifier": "original/lambda-py/python-reference/scope/locals-function-renamed.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/unboundlocal-after-del.py": {
      "identifier": "original/lambda-py/python-reference/scope/unboundlocal-after-del.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/test-builtin-scope.py": {
      "identifier": "original/lambda-py/python-reference/scope/test-builtin-scope.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/unbound-local.py": {
      "identifier": "original/lambda-py/python-reference/scope/unbound-local.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/unboundlocal-augassign.py": {
      "identifier": "original/lambda-py/python-reference/scope/unboundlocal-augassign.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-add.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-add.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-length.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-length.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-in.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-in.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-mul.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-mul.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/super/super-not-self.py": {
      "identifier": "original/lambda-py/python-reference/super/super-not-self.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-constructors.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-constructors.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/address-of-none.py": {
      "identifier": "original/lambda-py/python-reference/types/address-of-none.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/super/test-super.py": {
      "identifier": "original/lambda-py/python-reference/super/test-super.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/bitwise_test.py": {
      "identifier": "original/lambda-py/python-reference/types/bitwise_test.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-truth.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-truth.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/assign-to-self.py": {
      "identifier": "original/lambda-py/python-reference/types/assign-to-self.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/tuple/tuple-to-list.py": {
      "identifier": "original/lambda-py/python-reference/tuple/tuple-to-list.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test-add-with-funcs.py": {
      "identifier": "original/lambda-py/python-reference/types/test-add-with-funcs.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/test-builtin-scope-iter.py": {
      "identifier": "original/lambda-py/python-reference/scope/test-builtin-scope-iter.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test-aliasing.py": {
      "identifier": "original/lambda-py/python-reference/types/test-aliasing.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/scope/mutable-alias.py": {
      "identifier": "original/lambda-py/python-reference/scope/mutable-alias.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_booleans.py": {
      "identifier": "original/lambda-py/python-reference/types/test_booleans.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_div_zero.py": {
      "identifier": "original/lambda-py/python-reference/types/test_div_zero.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_comparisons.py": {
      "identifier": "original/lambda-py/python-reference/types/test_comparisons.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_simple_strings.py": {
      "identifier": "original/lambda-py/python-reference/types/test_simple_strings.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_pow.py": {
      "identifier": "original/lambda-py/python-reference/types/test_pow.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_floats.py": {
      "identifier": "original/lambda-py/python-reference/types/test_floats.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_string_slices.py": {
      "identifier": "original/lambda-py/python-reference/types/test_string_slices.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_int_float_primitives.py": {
      "identifier": "original/lambda-py/python-reference/types/test_int_float_primitives.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/scope/complex-defs.py": {
      "identifier": "original/lambda-py/scope/complex-defs.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_simple_string_ops.py": {
      "identifier": "original/lambda-py/python-reference/types/test_simple_string_ops.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/types_truthy1.py": {
      "identifier": "original/lambda-py/python-reference/types/types_truthy1.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/scope/complex-defs2.py": {
      "identifier": "original/lambda-py/scope/complex-defs2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/types_truthy2.py": {
      "identifier": "original/lambda-py/python-reference/types/types_truthy2.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/scope/nonlocal-from-class-body.py": {
      "identifier": "original/lambda-py/scope/nonlocal-from-class-body.py",
      "stdout": "",
      "stderr": "SyntaxError: no binding for nonlocal 'x' found\n",
      "returncode": 1,
      "exception": "SyntaxError",
      "message": " no binding for nonlocal 'x' found",
      "timeout": false
    },
    "original/lambda-py/scope/unboundlocal-augassign.py": {
      "identifier": "original/lambda-py/scope/unboundlocal-augassign.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_object_class.py": {
      "identifier": "original/lambda-py/python-reference/types/test_object_class.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "modified/k-python/testdocstring.py": {
      "identifier": "modified/k-python/testdocstring.py",
      "stdout": "",
      "stderr": "exception: name '__doc__' is not defined\n",
      "returncode": 1,
      "exception": "exception",
      "message": " name '__doc__' is not defined",
      "timeout": false
    },
    "modified/k-python/testsetattr4.py": {
      "identifier": "modified/k-python/testsetattr4.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "modified/k-python/fixed/testtuples7.py": {
      "identifier": "modified/k-python/fixed/testtuples7.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "koehl/except-target-delete.py": {
      "identifier": "koehl/except-target-delete.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "original/lambda-py/python-reference/types/test_dynamics.py": {
      "identifier": "original/lambda-py/python-reference/types/test_dynamics.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "koehl/do-not-run-init.py": {
      "identifier": "koehl/do-not-run-init.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "koehl/nonlocal-in-class.py": {
      "identifier": "koehl/nonlocal-in-class.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/lambda-py/scope/multiple-locals-calls.py": {
      "identifier": "original/lambda-py/scope/multiple-locals-calls.py",
      "stdout": "",
      "stderr": "AssertionError\n",
      "returncode": 1,
      "exception": "AssertionError",
      "message": "",
      "timeout": false
    },
    "koehl/non-string-keywords.py": {
      "identifier": "koehl/non-string-keywords.py",
      "stdout": "",
      "stderr": "TypeError: object is not callable\n",
      "returncode": 1,
      "exception": "TypeError",
      "message": " object is not callable",
      "timeout": false
    },
    "koehl/simple-property.py": {
      "identifier": "koehl/simple-property.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "koehl/mcs-attribute-lookup.py": {
      "identifier": "koehl/mcs-attribute-lookup.py",
      "stdout": "",
      "stderr": "",
      "returncode": 0,
      "exception": "",
      "message": "",
      "timeout": false
    },
    "original/k-python/programs/testsuper1.py": {
      "identifier": "original/k-python/programs/testsuper1.py",
      "stdout": "",
      "stderr": "",
      "returncode": -1,
      "exception": "",
      "message": "",
      "timeout": true
    },
    "original/lambda-py/bugs/memofib-decorator.py": {
      "identifier": "original/lambda-py/bugs/memofib-decorator.py",
      "stdout": "",
      "stderr": "",
      "returncode": -1,
      "exception": "",
      "message": "",
      "timeout": true
    }
  }
}